#!/bin/bash

git submodule add http://github.com/tpope/vim-fugitive.gi bundle/fugitive
git submodule add https://github.com/msanders/snipmate.vim.git bundle/snipmate
git submodule add https://github.com/tpope/vim-surround.git bundle/surround
git submodule add https://github.com/tpope/vim-git.git bundle/git
git submodule add https://github.com/scrooloose/syntastic.git bundle/syntastic

git submodule init
git submodule update
git submodule foreach git submodule init
git submodule foreach git submodule update

